### ISSUE TITLE
Honeypot

### ISSUE THREAD

**Issue by smartmeter** [drewhjelm/iis-hardening#1]
Hi does it include honeypot?

**Comment by drewhjelm** [comment]
No, this script does not include a honeypot. However, you could run the script on a server designated in your organization as a honeypot.

**Comment by smartmeter** [comment]
smartass :D  ok, seriously how can I get this to also pull in honeypots list

**Comment by drewhjelm** [comment]
Can you help me understand what you mean by pulling in a honeypot list? Are you trying to do some sort of routing from IIS to another server?

**Comment by smartmeter** [comment]
1.   Intro Honeypot https://en.wikipedia.org/wiki/Honeypot_(computing)

The honeypot list is updated to prevent spam, hackers, harvesters, dictionary attacks etc 

Example: There is a already a nice lib here by dejan, here is an example.. https://github.com/dejanstojanovic/MVC-Honeypot where he merged it to the IIS handler.
1.    Is it possible use your script to scan for a list of open/listening ports
2.    Clear the IIS cache
3.    Also I am trying to learn your lib, and add to it, I don't know PS. I found some stuff online, I am trying to add some functionality like changing/renaming the  admin policy for e.g. how can I add this to the script `Get-WMIObject Win32_UserAccount -Filter "Name -like 'admin*'" | Foreach-Object {$_.Rename("NewAdminName)")}`

**Comment by drewhjelm** [comment]
This script is just for hardening SSL on an IIS server right now. I hadn't considered adding spam filtering on the web server itself, but that's probably something better added to the application, like the library you mentioned. Normally I've also seen dictionary attacks mitigated in the application, rather than on the server. 

Preventing hackers from gaining access to the server really involves a lot of steps involving both securing infrastructure and the application development process. I prefer a defense-in-depth approach. For instance, if you're looking at defending a web server, you can look at putting a web application firewall like mod_security or another paid product in front of your application.

I think you're on the right track for renaming the local administrator account (https://stackoverflow.com/questions/5188917/powershells-script-to-re-name-local-guest-administrator-account). You'd want to add the rename account around line 204 (https://github.com/drewhjelm/iis-hardening/blob/master/configure%20IIS%20security.ps1) before the computer is restarted.

This script really wouldn't be used for scanning ports.

**Comment by smartmeter** [comment]
ok thanks for that explanation. 1) I wanted to add some snippets, but to understand, you're recommending that this is not the right place?

2) is IIS.net the best place for the modules and the security, I am trying to find out which modules are _highly_ recommended for IIS, interestingly your script comes out on top for security and _modules_ in some searches.

3) Also, in your opinion/guidance can you share some insight. For some of our ASP web-apps, we purchased a windows VPS to get more compute, if we are not IT admins, do you believe its too much of an effort to defend a server, and better off with a hosting provider like a smart asp.net etc. 

I also ask, because the hosting providers rarely (if any) mention any of the mod_securty or other WAF's 

I would like to see a recommendation on how you typically configure and defend your servers.

thanks again :+1:

**Comment by drewhjelm** [comment]
I have been unable to get to this since you last sent it over, so I apologize for my late reply.
1. What sort of snippets would you like to add to the script? 
2. Depending on what you're trying to secure, sometimes IIS is best, other times adding code to your ASP.NET application is best. There isn't really a silver bullet to hardening a web application.
3. There are plenty of hosting providers that offer WAF. I know that Edge Hosting offers a WAF with their hosting options. Also, if you're running AWS you can build your own WAF, either from a third party or by rolling your own with mod_security. I think the main thing I recommend for defending web application servers is to have the WAF in front of them. Defense-in-depth is really the key for a lot of security, and if you can have a server filtering many of the known attack types your web server will be safer.

**Comment by smartmeter** [comment]
ok thanks :+1:
